In [1]:
!pip install faiss-cpu
!pip install sentence-transformers

In [2]:
import pandas as pd

In [3]:
df =pd.read_csv("./example_data/sample_text.csv")

In [4]:
df.shape

(8, 2)

In [5]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [5]:
df.text

0        Meditation and yoga can improve mental health
1    Fruits, whole grains and vegetables helps cont...
2    These are the latest fashion trends for this week
3    Vibrant color jeans for male are becoming a trend
4                   The concert starts at 7 PM tonight
5    Navaratri dandiya program at Expo center in Mu...
6    Exciting vacation destinations for your next trip
7    Maldives and Srilanka are gaining popularity i...
Name: text, dtype: object

In [6]:
from sentence_transformers import SentenceTransformer

In [7]:
encoder =SentenceTransformer("all-mpnet-base-v2") #from HuggingsFace
vectors =encoder.encode(df.text)
vectors.shape

(8, 768)

In [8]:
vectors

array([[-0.00247395,  0.03626722, -0.05290459, ..., -0.09152356,
        -0.03970001, -0.04330489],
       [-0.03357267,  0.00980519, -0.03250129, ..., -0.05165466,
         0.02245887, -0.03156182],
       [-0.01865322, -0.04051318, -0.01235387, ...,  0.00610586,
        -0.07179645,  0.02773851],
       ...,
       [-0.00066458,  0.04252127, -0.05645508, ...,  0.0131547 ,
        -0.03183567, -0.04357665],
       [-0.03317153,  0.03252455, -0.02484838, ...,  0.0117442 ,
         0.05747124,  0.00571023],
       [-0.00166395,  0.00413828, -0.04597083, ...,  0.02008527,
         0.05656243, -0.00161596]], dtype=float32)

In [9]:
dim =vectors.shape[1]
dim

768

In [10]:
import faiss
#create index for the vectors
index =faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x784a0ec5ee50> >

In [11]:
index.add(vectors) #instantialize the index with the vectors

In [12]:
search_query ="I want to buy a polo t-shirt"
vec =encoder.encode(search_query)
vec.shape

(768,)

In [13]:
import numpy as np
svec =np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [15]:
distance, I =index.search(svec, k=3)

In [16]:
I

array([[3, 2, 5]])

In [17]:
df.loc[[3,2,5]]

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion
5  Navaratri dandiya program at Expo center in Mu...    Event

In [19]:
distance

array([[1.3844837, 1.4039097, 1.7325616]], dtype=float32)

In [20]:
search_query

'I want to buy a polo t-shirt'

In [21]:
# you can see that the two results from the dataframe are similar to a search_query

In [22]:
search_query ="An apple a day keeps the doctor away"
vec =encoder.encode(search_query)
vec.shape

(768,)

In [23]:
svec =np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [24]:
index.search(svec, k=2)

(array([[1.3433158, 1.7125273]], dtype=float32), array([[1, 0]]))

In [25]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [27]:
 # you can see that the two results from the dataframe are similar to this , because of talking about health problem